### ISSUE TITLE
Are advanced features of services workers supported ?

### ISSUE THREAD

**Issue by Aarbel** [xtools-at/iOS-PWA-Wrapper#2] opened 2018-09-22 10:12 UTC
1 - Does this wrapper support [Push Notifications](https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications) ? (linked with the Native notifications and badges system)

2 - Does this wrapper support [Background Sync](https://developers.google.com/web/updates/2015/12/background-sync) ?

**Comment by Aarbel** [comment] 2018-09-22 10:14
The question could be extended to your Android and Electron repos, do they manage this extended features ? :)

**Comment by xtools-at** [comment] 2018-09-23 09:53
No service worker support on iOS yet

**Comment by Aarbel** [comment] 2018-09-23 10:09
Yes, but a wrapper can hack the way the webview caches stuff and handle service-workers.js file ;)

**Comment by xtools-at** [comment] 2018-09-23 11:05
No it can't, on iOS we only have AppCache support for now as Safari Webview / WebKit doesn't support ServiceWorker

**Comment by Aarbel** [comment] 2018-09-23 15:00
Cordova finds a way, so we can find a way yes :)

I'm not comfy with native stuff, so i'll try to federate Paris open source developers to contribute.

I just have one question : what is the link with PWA if this repo doesn't manage Service Workers ? Maybe i missed a part of this repo that manage PWA features.

**Comment by clovisnicolas** [comment] 2018-09-24 13:04
@xtools-at https://webkit.org/status/ states that Service Workers are supported, is it something new, or does that not apply to iOS?

**Comment by Aarbel** [comment] 2018-09-24 18:44
Check this post : https://webkit.org/blog/8090/workers-at-your-service/

**Comment by lgandecki** [comment] 2018-10-19 06:04
I have the same question as @Aarbel  - what does this repo has to do with PWA if service workers are not supported? Did anyone figure this out? :)

**Comment by lgandecki** [comment] 2018-10-19 06:10
The documentation says "Provided your Web App is Offline-capable, it only needs an Internet connection on the first startup. If this fails, it shows a native refresh widget.", so how is that achieved without serviceworkers? Or is this a copy paste from the android repo where this works?

I actually tried this in a simulator on an app that is offline-capable, and it didn't work when I disconnected my wifi connection (it worked in chrome when I hit refresh, but closing and opening the app in simulator just showed a spinner)

**Comment by xtools-at** [comment] 2018-10-22 09:22
the README also states
> For bringing offline-capabilities to your Web App on Safari and iOS' embedded WebKit browser, you have to use AppCache. Service Worker API is not yet supported in WebKit, so you might want to use something like Appcache Webpack Plugin to make your PWA offline-accessible on iOS in a somewhat easy way.

the issue is that Safari didn't incorporate those WebKit changes yet (as of iOS 11.4), but hopefully soon (can't find the source right now) - maybe it's already upgraded in iOS 12, may be worth re-testing.

They even had major issues with AppCache for 2 or 3 major iOS versions (= years) until everything worked as intended, so I guess even if ServiceWorker is there, it will be buggy as hell atm.

As of now, you need to have an AppCache-fallback to support Safari and it's WebView on iOS, and you'll have to have it to support older iOS devices.

C'mon guys, it's not that hard, there's a webpack plugin which can be set up quite easily :) I guess

**Comment by lgandecki** [comment] 2018-10-22 14:10
thanks a lot for replying. I don't know how I missed that part! It makes sense. I think there is this common (mis?) understanding that PWA implies Service Workers, but, it makes sense that that doesn't technically have to be the case.

**Comment by xtools-at** [comment] 2018-11-26 16:00
So to sum up, ServiceWorker API is not yet ready for iOS WebViews - according to [this discussion](https://stackoverflow.com/a/51299265/4147032), Safari in iOS 12 still lacks support for notifications, couldn't find any info on ServiceWorker support in general in Safari/Safari WebView.

To make your app offline accessible on iOS <= 12 (and probably subsequent versions; + you might want to support devices on older iOS versions too), please use _AppCache_ in your PWA _additionally_ to ServiceWorkers. You may set up and use [this Webpack plugin](https://github.com/lettertwo/appcache-webpack-plugin) to create the necessary files for you.

**Closed by xtools-at** 2018-11-26 16:00 UTC

**Comment by OzairP** [comment] 2019-08-28 22:56
I have been interested in this for a while and I think I may have a valid solution could work.
With `WKWebView` monkey patch Service Worker with `WKScriptMessageHandler`.
When a service worker is attempting to install, that JavaScript worker file is run in a `JSVirtualMachine` whose environment is up to spec with [`ServiceWorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope).
However this is a pretty hefty task with Swift managing a bus between the JS VM and the WKWebView.

Maybe `pushMessage` and the notifications API in SW should be feasible at least for now?
